# Generated by Django 5.0.14 on 2026-09-01 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_approved_at_customer_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('GENERAL_ANNOUNCEMENT', 'General Announcement'), ('REPAYMENT_REMINDER', 'Repayment Reminder'), ('CONTRIBUTION_REMINDER', 'Contribution Reminder'), ('OVERDUE_REPAYMENT_REMINDER', 'Overdue Repayment Reminder'), ('LOAN_NOTIFICATION', 'Loan Notification'), ('ACCOUNT_APPROVAL', 'Account Approval'), ('ACCOUNT_ACTIVATION', 'Account Activation'), ('SUSU_ACTIVATION', 'Contribution/Susu Activation'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('CUSTOM_MESSAGE', 'Custom Message')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('trigger', models.CharField(choices=[('SEND_NOW', 'Send Now'), ('SCHEDULE', 'Schedule for Later')], default='SEND_NOW', max_length=20)),
                ('target_group', models.CharField(choices=[('ALL_ACTIVE', 'All Active Customers'), ('ACTIVE_LOANS', 'Customers with Active Loans'), ('OUTSTANDING_REPAYMENTS', 'Customers with Outstanding Repayments'), ('OVERDUE_REPAYMENTS', 'Customers with Overdue Repayments'), ('SUSU_ACCOUNTS', 'Customers with Contributions/Susu Accounts'), ('DUE_CONTRIBUTIONS', 'Customers with Due Contributions'), ('OVERDUE_CONTRIBUTIONS', 'Customers with Overdue Contributions'), ('RECENTLY_APPROVED', 'Recently Approved Customers'), ('RECENTLY_ACTIVATED', 'Recently Activated Customers'), ('MANUAL_SELECTION', 'Manually Selected Customers')], max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('manual_customer_ids', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('valid_phone_count', models.PositiveIntegerField(default=0)),
                ('missing_phone_count', models.PositiveIntegerField(default=0)),
                ('excluded_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('sms_units', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Campaign',
                'verbose_name_plural': 'SMS Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('delivery_status', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sms_units', models.PositiveIntegerField(default=1)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('unique_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='campaigns.smscampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_message_logs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Campaign SMS Log',
                'verbose_name_plural': 'Campaign SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('GENERAL_ANNOUNCEMENT', 'General Announcement'), ('REPAYMENT_REMINDER', 'Repayment Reminder'), ('CONTRIBUTION_REMINDER', 'Contribution Reminder'), ('OVERDUE_REPAYMENT_REMINDER', 'Overdue Repayment Reminder'), ('LOAN_NOTIFICATION', 'Loan Notification'), ('ACCOUNT_APPROVAL', 'Account Approval'), ('ACCOUNT_ACTIVATION', 'Account Activation'), ('SUSU_ACTIVATION', 'Contribution/Susu Activation'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('CUSTOM_MESSAGE', 'Custom Message')], max_length=30)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
