# Generated by Django 5.2.15 on 2026-09-02 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('susu', '0002_susuaccount_activated_at_alter_susuaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessagelog',
            name='susu_account',
            field=models.ForeignKey(blank=True, help_text='The specific Susu account this message was sent for, when a customer has multiple active accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_message_logs', to='susu.susuaccount'),
        ),
    ]
