# Generated by Django 5.2.15 on 2026-08-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('PAYSTACK', 'Paystack (Online)'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
