# Generated by Django 5.0.14 on 2026-09-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='susuaccount',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='susuaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], default='INACTIVE', max_length=20),
        ),
    ]
