# Generated by Django 5.2.15 on 2026-08-26 16:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Loan Policy', max_length=200)),
                ('minimum_membership_days', models.PositiveIntegerField(default=90, help_text='Minimum days since registration')),
                ('minimum_contribution_days', models.PositiveIntegerField(default=90, help_text='Minimum days of active contributing')),
                ('minimum_successful_contributions', models.PositiveIntegerField(default=12, help_text='Minimum number of verified successful contributions')),
                ('minimum_savings', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum total verified savings (GHS)', max_digits=12)),
                ('maximum_loan_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Maximum loan amount as multiplier of savings', max_digits=4)),
                ('maximum_active_loans', models.PositiveIntegerField(default=1)),
                ('maximum_missed_periods', models.PositiveIntegerField(default=2, help_text='Maximum allowed missed contribution periods')),
                ('waiting_period_days', models.PositiveIntegerField(default=7, help_text='Days after registration before eligibility check')),
                ('require_kyc', models.BooleanField(default=True)),
                ('require_good_repayment_history', models.BooleanField(default=True)),
                ('block_overdue_customers', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='eligibility_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='EligibilityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField(default=False)),
                ('maximum_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('eligibility_score', models.PositiveIntegerField(default=0)),
                ('passed_criteria', models.JSONField(blank=True, default=list)),
                ('failed_criteria', models.JSONField(blank=True, default=list)),
                ('membership_months', models.PositiveIntegerField(default=0)),
                ('required_membership_months', models.PositiveIntegerField(default=0)),
                ('successful_contributions', models.PositiveIntegerField(default=0)),
                ('required_contributions', models.PositiveIntegerField(default=0)),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('minimum_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('missed_periods', models.PositiveIntegerField(default=0)),
                ('max_missed_periods', models.PositiveIntegerField(default=0)),
                ('active_loans', models.PositiveIntegerField(default=0)),
                ('has_overdue', models.BooleanField(default=False)),
                ('is_kyc_complete', models.BooleanField(default=True)),
                ('contribution_period_months', models.PositiveIntegerField(default=0)),
                ('required_contribution_months', models.PositiveIntegerField(default=0)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_audits', to='customers.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_audits', to='loans.loanpolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
