# Generated by Django 5.0.14 on 2026-08-26 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('CONTRIBUTION_CREATED', 'Contribution Created'), ('WITHDRAWAL_CREATED', 'Withdrawal Created'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('LOAN_CREATED', 'Loan Created'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('REPAYMENT_CREATED', 'Repayment Created'), ('USER_CREATED', 'User Created'), ('USER_PERMISSION_CHANGED', 'User Permission Changed'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed')], max_length=30)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
