# Generated by Django 5.0.14 on 2026-09-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('SUSU_ACCOUNT_ACTIVATED', 'Susu Account Activated'), ('CONTRIBUTION_CREATED', 'Contribution Created'), ('WITHDRAWAL_CREATED', 'Withdrawal Created'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('LOAN_CREATED', 'Loan Created'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('REPAYMENT_CREATED', 'Repayment Created'), ('USER_CREATED', 'User Created'), ('USER_PERMISSION_CHANGED', 'User Permission Changed'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed')], max_length=30),
        ),
    ]
