# Generated by Django 5.0.14 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsnotification',
            old_name='brevo_message_id',
            new_name='provider_message_id',
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
