# Generated by Django 5.0.14 on 2026-09-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sailup_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='notification_type',
            field=models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('SUSU_ACTIVATED', 'Susu Account Activated'), ('PHONE_VERIFIED', 'Phone Verified'), ('CONTRIBUTION', 'Contribution'), ('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('LOAN_APPLICATION', 'Loan Application'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('REPAYMENT_REMINDER', 'Repayment Reminder'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
